---
Name: appcustomroutes
After:
  - '#app'
---
Director:
  rules:
    '' : 'HomeController'
    'orient' : 'OrientController'
    'sandbox' : 'SandboxController'
    'performance' : 'PerformanceController'
